### ISSUE TITLE
Transiciones de en Contacto de Fechas de ingreso confusas

### ISSUE THREAD

**Issue by nicolaslarrea** [maxpowergit/app-donacion-corneas#13]
Las transisciones que usan DatoTemporalDonante, se suceden entre sí, pero no hay ningún feedback de que está pasando. No queda claro si estás ingresando dos veces la misma fecha, si pasaste a la otra. Hay que repensarlo.

**Comment by mauriciopasquier** [comment]
Pienso que estilar el input que está "en foco" en ese momento sería una buena solución, para todos los inputs.

**Comment by mauriciopasquier** [comment]
Reordenamos los inputs temporales al final del formulario y sacamos las transiciones.
