### ISSUE TITLE
Flecha de scrollView en escena contraindicaciones.

### ISSUE THREAD

**Issue by nicolaslarrea** [maxpowergit/app-donacion-corneas#20]
La escena contraindicaciones tiene una lista larga de contraindicaciones. Y no queda claro si se ven o no.
Se podría poner una flechita para abajo que muestre que abajo hay mas, o que el botón no se habilite hasta que el scroll esté en el fndo.

**Comment by mauriciopasquier** [comment]
Discutimos sobre otro tipo de feedback como sombras en header, separación del footer, etc
