### ISSUE TITLE
Botón salir de última escena

### ISSUE THREAD

**Issue by nicolaslarrea** [maxpowergit/app-donacion-corneas#21]
El botón salir de la última escena debiera, borrar el estado de la app (salvo el teléfono del coordinador) y navegar hacia escena requisitos antes de cerrarse

**Comment by mauriciopasquier** [comment]
Parece que está complicado resetear el state con [redux-persist](
https://github.com/rt2zz/redux-persist/issues/770) y que la librería recomendada para hacer (redux-reset) [no anda](https://github.com/wwayne/redux-reset/issues/7) con la última versión de `redux-persist`. Podríamos probar [reseteando la app entera](https://github.com/avishayil/react-native-restart) 
pero si ya vamos a usar una librería para resetear la app, podemos usar la [librería para cerrarla bien](https://github.com/wumke/react-native-exit-app) y listo...

**Comment by nicolaslarrea** [comment]
En la rama exit_app hay una potencial solución a esto. Pero para que funcione hay que ejectar la app.
Una vez ejectada, para emular la app hay que hacer mas pasos.
 
1- En el root del proyecto correr "expo eject" y elegir la opción que dice ExpoKit
2- linkear la librería react-native: "link react-native-exit-app"
3- Con el servidor de expo corriendo, hacer en la nueva carpeta android "./gradlew installDevKernelDebug"

Dejaría esta rama con los cambios, y solo la mergería de ser necesario para armar los buils. Por ahora aunque soluciona el tema del botón final, complica el proceso de trabajo.

**Comment by mauriciopasquier** [comment]
Oka

**Comment by nicolaslarrea** [comment]
Al haber ejectado la App de expo, ya no presenta los problemas que tenía antes para usar está librería. 
El funcionamiento está actualmente implementado.
