### ISSUE TITLE
Boton footer tapa el ingreso telefónico.

### ISSUE THREAD

**Issue by nicolaslarrea** [maxpowergit/app-donacion-corneas#23]
En ambas escenas Ingreso y teléfono cuando se levanta el teclado para ingresar el número, queda a medio tapar el input donde se lo está ingresando. 
Se me ocurren dos posibles soluciones:
- Hacer invisible el boton footer cuando se levanta el teclado.
- Achicar el icono del teléfono para que haga espacio en los celulares chicos.
La primera me parece más definitiva.

**Comment by mauriciopasquier** [comment]
Me gusta más la de achicar o incluso desaparecer el ícono, porque los botones son funcionalidad, y además vamos a tener un botón extra de "buscar en agenda"
