### ISSUE TITLE
ScrollView para escena contacto

### ISSUE THREAD

**Issue by nicolaslarrea** [maxpowergit/app-donacion-corneas#25]
En celulares chicos, la escena Contacto no se muestra entera, y por alguna razón no scrollea para abajo. A veces, el último campo queda sin poder completarse entonces.

**Comment by nicolaslarrea** [comment]
La escena ahora se muestra bien, si es necesario en celulares chicos scrollea para abajo. Igualmente, los lugares donde tocar son incómodos. Quedará para la 3.0 la mejora.

**Comment by mauriciopasquier** [comment]
Entonces era sacar el estilo no más?

**Comment by nicolaslarrea** [comment]
En lo que respecta a "bug", si. Había un flex:1 que estaba haciendo que no scrollee. Esta funcional, necesitaría un "enhancement" en relación al diseño. El scroll, es incómodo y la info está muy junta. Pero no es este Issue.
